// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/events": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/verify": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/:userId": {
    params: {
      "userId": string;
    };
  };
  "/:userId/profile": {
    params: {
      "userId": string;
    };
  };
  "/:userId/admin": {
    params: {
      "userId": string;
    };
  };
  "/:userId/admin/users": {
    params: {
      "userId": string;
    };
  };
  "/:userId/admin/users/:reqUserId": {
    params: {
      "userId": string;
      "reqUserId": string;
    };
  };
  "/:userId/admin/events": {
    params: {
      "userId": string;
    };
  };
  "/:userId/admin/events/:eventId": {
    params: {
      "userId": string;
      "eventId": string;
    };
  };
  "/:userId/admin/developer": {
    params: {
      "userId": string;
    };
  };
  "/:userId/instructor": {
    params: {
      "userId": string;
    };
  };
  "/:userId/help": {
    params: {
      "userId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/events" | "/auth" | "/auth/verify" | "/about" | "/:userId" | "/:userId/profile" | "/:userId/admin" | "/:userId/admin/users" | "/:userId/admin/users/:reqUserId" | "/:userId/admin/events" | "/:userId/admin/events/:eventId" | "/:userId/admin/developer" | "/:userId/instructor" | "/:userId/help";
  };
  "pages/home/page.tsx": {
    id: "pages/home/page";
    page: "/";
  };
  "features/events/page/events-page.tsx": {
    id: "features/events/page/events-page";
    page: "/events";
  };
  "pages/auth/page.tsx": {
    id: "pages/auth/page";
    page: "/auth" | "/auth/verify";
  };
  "pages/auth/outlets/form-view.tsx": {
    id: "pages/auth/outlets/form-view";
    page: "/auth";
  };
  "pages/auth/outlets/verify-view.tsx": {
    id: "pages/auth/outlets/verify-view";
    page: "/auth/verify";
  };
  "pages/about/page.tsx": {
    id: "pages/about/page";
    page: "/about";
  };
  "features/dashboard/page/dashboard-page.tsx": {
    id: "features/dashboard/page/dashboard-page";
    page: "/:userId" | "/:userId/profile" | "/:userId/admin" | "/:userId/admin/users" | "/:userId/admin/users/:reqUserId" | "/:userId/admin/events" | "/:userId/admin/events/:eventId" | "/:userId/admin/developer" | "/:userId/instructor" | "/:userId/help";
  };
  "features/dashboard/page/views/main-view.tsx": {
    id: "features/dashboard/page/views/main-view";
    page: "/:userId";
  };
  "features/dashboard/page/views/profile-view.tsx": {
    id: "features/dashboard/page/views/profile-view";
    page: "/:userId/profile";
  };
  "features/dashboard/page/views/admin-view.tsx": {
    id: "features/dashboard/page/views/admin-view";
    page: "/:userId/admin";
  };
  "features/dashboard/page/views/admin/users/users-view.tsx": {
    id: "features/dashboard/page/views/admin/users/users-view";
    page: "/:userId/admin/users";
  };
  "features/dashboard/page/views/admin/users/user-view.tsx": {
    id: "features/dashboard/page/views/admin/users/user-view";
    page: "/:userId/admin/users/:reqUserId";
  };
  "features/dashboard/page/views/admin/events/events-view.tsx": {
    id: "features/dashboard/page/views/admin/events/events-view";
    page: "/:userId/admin/events";
  };
  "features/dashboard/page/views/admin/events/event-view.tsx": {
    id: "features/dashboard/page/views/admin/events/event-view";
    page: "/:userId/admin/events/:eventId";
  };
  "features/dashboard/page/views/developer-view.tsx": {
    id: "features/dashboard/page/views/developer-view";
    page: "/:userId/admin/developer";
  };
  "features/dashboard/page/views/instructors/instructor-view.tsx": {
    id: "features/dashboard/page/views/instructors/instructor-view";
    page: "/:userId/instructor";
  };
  "features/dashboard/page/views/help-view.tsx": {
    id: "features/dashboard/page/views/help-view";
    page: "/:userId/help";
  };
};