// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/events": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/profile/:userId": {
    params: {
      "userId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/events" | "/auth" | "/about" | "/profile/:userId";
  };
  "features/home/Home.tsx": {
    id: "features/home/Home";
    page: "/";
  };
  "features/events/EventsPage.tsx": {
    id: "features/events/EventsPage";
    page: "/events";
  };
  "features/auth/AuthPage.tsx": {
    id: "features/auth/AuthPage";
    page: "/auth";
  };
  "features/about/AboutPage.tsx": {
    id: "features/about/AboutPage";
    page: "/about";
  };
  "features/dashboard/DashboardPage.tsx": {
    id: "features/dashboard/DashboardPage";
    page: "/profile/:userId";
  };
};