// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/events": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/verify": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/users": {
    params: {};
  };
  "/dashboard/users/:userId": {
    params: {
      "userId": string;
    };
  };
  "/dashboard/events": {
    params: {};
  };
  "/dashboard/dev": {
    params: {};
  };
  "/dashboard/events/:eventId": {
    params: {
      "eventId": string;
    };
  };
  "/dashboard/auth": {
    params: {};
  };
  "/dashboard/instructor": {
    params: {};
  };
  "/dashboard/help": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/events" | "/about" | "/auth" | "/auth/verify" | "/*" | "/dashboard" | "/dashboard/settings" | "/dashboard/users" | "/dashboard/users/:userId" | "/dashboard/events" | "/dashboard/dev" | "/dashboard/events/:eventId" | "/dashboard/auth" | "/dashboard/instructor" | "/dashboard/help";
  };
  "pages/public-layout.tsx": {
    id: "pages/public-layout";
    page: "/" | "/events" | "/about" | "/auth" | "/auth/verify" | "/*";
  };
  "pages/home/page.tsx": {
    id: "pages/home/page";
    page: "/";
  };
  "pages/events/page.tsx": {
    id: "pages/events/page";
    page: "/events";
  };
  "pages/about/page.tsx": {
    id: "pages/about/page";
    page: "/about";
  };
  "pages/auth/page.tsx": {
    id: "pages/auth/page";
    page: "/auth" | "/auth/verify";
  };
  "pages/auth/outlets/form-view.tsx": {
    id: "pages/auth/outlets/form-view";
    page: "/auth";
  };
  "pages/auth/outlets/verify-view.tsx": {
    id: "pages/auth/outlets/verify-view";
    page: "/auth/verify";
  };
  "pages/not-found.tsx": {
    id: "pages/not-found";
    page: "/*";
  };
  "pages/dashboard/page.tsx": {
    id: "pages/dashboard/page";
    page: "/dashboard" | "/dashboard/settings" | "/dashboard/users" | "/dashboard/users/:userId" | "/dashboard/events" | "/dashboard/dev" | "/dashboard/events/:eventId" | "/dashboard/auth" | "/dashboard/instructor" | "/dashboard/help";
  };
  "pages/dashboard/outlets/base/home-view.tsx": {
    id: "pages/dashboard/outlets/base/home-view";
    page: "/dashboard";
  };
  "pages/dashboard/outlets/base/profile-view.tsx": {
    id: "pages/dashboard/outlets/base/profile-view";
    page: "/dashboard/settings";
  };
  "pages/dashboard/outlets/admin/users/users-view.tsx": {
    id: "pages/dashboard/outlets/admin/users/users-view";
    page: "/dashboard/users";
  };
  "pages/dashboard/outlets/admin/users/user/user-view.tsx": {
    id: "pages/dashboard/outlets/admin/users/user/user-view";
    page: "/dashboard/users/:userId";
  };
  "pages/dashboard/outlets/admin/events/events-view.tsx": {
    id: "pages/dashboard/outlets/admin/events/events-view";
    page: "/dashboard/events";
  };
  "pages/dashboard/outlets/admin/dev-view.tsx": {
    id: "pages/dashboard/outlets/admin/dev-view";
    page: "/dashboard/dev";
  };
  "pages/dashboard/outlets/admin/events/event/event-view.tsx": {
    id: "pages/dashboard/outlets/admin/events/event/event-view";
    page: "/dashboard/events/:eventId";
  };
  "pages/dashboard/outlets/admin/auth-view.tsx": {
    id: "pages/dashboard/outlets/admin/auth-view";
    page: "/dashboard/auth";
  };
  "pages/dashboard/outlets/admin/instructor-view.tsx": {
    id: "pages/dashboard/outlets/admin/instructor-view";
    page: "/dashboard/instructor";
  };
  "pages/dashboard/outlets/base/help-view.tsx": {
    id: "pages/dashboard/outlets/base/help-view";
    page: "/dashboard/help";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/public-layout": typeof import("./app/pages/public-layout.tsx");
  "pages/home/page": typeof import("./app/pages/home/page.tsx");
  "pages/events/page": typeof import("./app/pages/events/page.tsx");
  "pages/about/page": typeof import("./app/pages/about/page.tsx");
  "pages/auth/page": typeof import("./app/pages/auth/page.tsx");
  "pages/auth/outlets/form-view": typeof import("./app/pages/auth/outlets/form-view.tsx");
  "pages/auth/outlets/verify-view": typeof import("./app/pages/auth/outlets/verify-view.tsx");
  "pages/not-found": typeof import("./app/pages/not-found.tsx");
  "pages/dashboard/page": typeof import("./app/pages/dashboard/page.tsx");
  "pages/dashboard/outlets/base/home-view": typeof import("./app/pages/dashboard/outlets/base/home-view.tsx");
  "pages/dashboard/outlets/base/profile-view": typeof import("./app/pages/dashboard/outlets/base/profile-view.tsx");
  "pages/dashboard/outlets/admin/users/users-view": typeof import("./app/pages/dashboard/outlets/admin/users/users-view.tsx");
  "pages/dashboard/outlets/admin/users/user/user-view": typeof import("./app/pages/dashboard/outlets/admin/users/user/user-view.tsx");
  "pages/dashboard/outlets/admin/events/events-view": typeof import("./app/pages/dashboard/outlets/admin/events/events-view.tsx");
  "pages/dashboard/outlets/admin/dev-view": typeof import("./app/pages/dashboard/outlets/admin/dev-view.tsx");
  "pages/dashboard/outlets/admin/events/event/event-view": typeof import("./app/pages/dashboard/outlets/admin/events/event/event-view.tsx");
  "pages/dashboard/outlets/admin/auth-view": typeof import("./app/pages/dashboard/outlets/admin/auth-view.tsx");
  "pages/dashboard/outlets/admin/instructor-view": typeof import("./app/pages/dashboard/outlets/admin/instructor-view.tsx");
  "pages/dashboard/outlets/base/help-view": typeof import("./app/pages/dashboard/outlets/base/help-view.tsx");
};